### ISSUE TITLE
Plugin won't allow Homebridge to start

### ISSUE THREAD

**Issue by PointingP** [paolotremadio/homebridge-automation-lifx-colour-palettes#9]
I'm getting the following error message in the log:

The plugin "homebridge-automation-lifx-colour-palettes" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!

Homebridge won't start, until I disable the plugin. Any ideas on what I'm doing wrong? I'm using the sample config and sample palette.json under homebridge folder

**Comment by puk-estar** [comment]
Your homebridge is not starting for some other reasons. Could you please paste the complete log? That line you've posted is a warning and not an error, it won't be blocking homebridge from starting

**Comment by paolotremadio** [comment]
Your homebridge is not starting for some other reasons. Could you please paste the complete log? That line you've posted is a warning and not an error, it won't be blocking homebridge from starting

**Comment by PointingP** [comment]
Wow, that was a fast reply.
Here is the other red text i'm getting, which only comes up when i enable this plugin:

TypeError: characteristic.internalHAPRepresentation is not a function
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:648:82
    at Array.map (<anonymous>)
    at Switch.Service.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:648:45)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1081:54
    at Array.map (<anonymous>)
    at Accessory.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1081:31)
    at Bridge.Accessory.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1088:36)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1196:25)
    at BridgeService.publishBridge (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:215:17)
    at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:186:24)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:177:24
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:176:5)
